GET http://0.0.0.0:8080/auth/all

###
GET http://0.0.0.0:8080/auth 
Content-Type: application/json

{
  "email": "fake@email.com",
  "password": "12341234"
}

###
POST http://0.0.0.0:8080/auth 
Content-Type: application/json

{
  "email": "cake@email.com",
  "password": "12341234"
}

###
DELETE http://0.0.0.0:8080/auth 
Content-Type: application/json

{
  "email": "cake@email.com"
}


// Notes
###
GET http://0.0.0.0:8080/notes/6468c43eac69061ee0519008
Content-Type: application/json

{
  "user_id": "6468c43eac69061ee0519008"
}

###
POST http://0.0.0.0:8080/notes/6468c43eac69061ee0519008
Content-Type: application/json

{
  "title": "aTitle",
  "content": "the the the content content content",
  "tags": []
}

###
PATCH http://0.0.0.0:8080/notes
Content-Type: application/json

{
  "user_id": "6468c43eac69061ee0519008",
  "note_id": "646a33576366824ad14cc663",
  "title": "Title Updated"
}

###
PATCH http://0.0.0.0:8080/notes/tags/6468c43eac69061ee0519008
Content-Type: application/json

[
  {
  "note_id": "646a33576366824ad14cc663",
  "tag_id": "646a5a22e41c7965ea5ad991",
  "name": "older"
  },
  {
  "note_id": "646a33576366824ad14cc663",
  "tag_id": "646a5a22e41c7965ea5ad991",
  "name": "olderer"
  }
]

###
DELETE http://0.0.0.0:8080/notes
Content-Type: application/json

{
  "user_id": "6468c43eac69061ee0519008",
  "note_id": "646a33dcdca7b168d827af98"
}


// Tags
###
GET http://0.0.0.0:8080/tags


###
POST http://0.0.0.0:8080/tags
Content-Type: application/json

{
  "name": "new"
}

###
PATCH http://0.0.0.0:8080/tags
Content-Type: application/json

{
  "id": "646a5f5691c02d9506e8fe20",
  "name": "other"
}

###
DELETE http://0.0.0.0:8080/tags
Content-Type: application/json

{
  "id": "646a5f5691c02d9506e8fe20"
}